### ISSUE TITLE
WHY!!!!!

### ISSUE THREAD

**Issue by MyCoolStrawSIr** [TheCBProject/Translocators#32]
Translocators used to be so nice in 1.7.10. I could place them where ever i needed them to go... Now in 1.10.2 I cant even use them because they can barely be placed on anything!!!!! I can place them on places where i DONT need them, but when it comes to places i need them i CANT!!!! It is so frustrating! Now IDK if the mod was designed that way or it's just 1.10.2 screwing with things. If it's not 1.10.2 that is the problem then the mod is not worth it any more.

**Comment by covers1624** [comment]
So this is due to the new capability system in forge, 1.12+ translocators is getting a full rewrite to be a full multipart with fmp, all the logic behind the item translocator will be rewritten, depending on how breaking the changes are I may pull it back to 1.11, highly doubtful it will be pulled back to 1.10.

**Comment by MyCoolStrawSIr** [comment]
It just sucks i cant use them like i used to in 1.10 maybe there is a mod
pack in the elevated versions i moght be interested in

**Comment by covers1624** [comment]
This was resolved a while ago.
