### ISSUE TITLE
Glowstone stops it working

### ISSUE THREAD

**Issue by Hypermobile** [TheCBProject/Translocators#35]
Don't know why, but putting glowstone on a translocator causes it to stop transferring. Any ideas?

**Comment by covers1624** [comment]
Without any screenshots or a video, i have absolutely no idea why it would stop, adding glowstone causes Item translocators to transfer up to a stack per tick and on a liquid translocator up to a bucket per tick, its possible there could be some other desync happening in your world that makes it look like it hasn't because it transfered so fast.

**Comment by covers1624** [comment]
No info was given as requested.
